services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      graylog:
        condition: "service_started"
    environment:
      # Database configuration
      - POSTGRES_NAME=${POSTGRES_NAME}  # Name of the PostgreSQL database, e.g., shipment_db
      - POSTGRES_USER=${POSTGRES_USER}  # Username for the PostgreSQL database, e.g., shipment_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # Password for the PostgreSQL database, e.g., securepassword123
      - POSTGRES_HOST=${POSTGRES_HOST}  # Hostname of the PostgreSQL database, e.g., db
      - POSTGRES_PORT=${POSTGRES_PORT}  # Port number of the PostgreSQL database, e.g., 5432

      # Django settings
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}  # Secret key for Django application, e.g., supersecretkey
      - DJANGO_DEBUG=True  # Debug mode for Django application (True for development, False for production), e.g., False

      # Email settings
      - EMAIL_HOST=mail.smtp2go.com  # SMTP server host, e.g., smtp.gmail.com
      - EMAIL_PORT=2525  # SMTP server port, e.g., 587
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}  # SMTP server user, e.g., your-email@gmail.com
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}  # SMTP server password, e.g., yourpassword
      - EMAIL_USE_TLS="False"  # Use TLS for email (True or False), e.g., True
      - DEFAULT_FROM_EMAIL=noreply@bpm-training.net  # Default sender email address, e.g., your-email@gmail.com
      - INTERNAL_STAFF_EMAILS=zaidalshreef@gmail.com,zhoutai1990@gmail.com  # Comma-separated list of internal staff emails, e.g., staff1@example.com,staff2@example.com

      # API keys
      - GOOGLE_MAPS_API_KEY=AIzaSyA6mmmEz_JCmb6p-yD6RnDPtRt7o4SXjh8  # API key for Google Maps, e.g., your_google_maps_api_key
      - SALLA_API_KEY=8d20a45d-ca26-4910-b6ca-1b49f0298632  # API key for Salla, e.g., your_salla_api_key
      - SALLA_API_SECRET=37686b0677d48c01cc8eb9b7ad2e2cea  # API secret for Salla, e.g., your_salla_api_secret

      # Security settings
      - ALLOWED_HOSTS=techsynapse.org  # Comma-separated list of allowed hosts, e.g., techsynapse.org,localhost
      - CSRF_TRUSTED_ORIGINS=https://techsynapse.org,http://localhost  # Comma-separated list of CORS allowed origins, e.g., https://techsynapse.org
      - PORT=8000  # Port number for the Django application, e.g., 8080
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
    restart: unless-stopped


  db:
    image: postgres
    restart: always
    user: postgres
    depends_on:
      graylog:
        condition: "service_started"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"


  # Graylog stores configuration in MongoDB
  mongo:
    image: mongo:6.0.5-jammy
    container_name: mongodb
    volumes:
      - "mongo_data:/data/db"
    restart: always

  # The logs themselves are stored in Opensearch
  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=SetPassw0rdL3ttersAndNumb3r5"
    volumes:
      - "log_data:/usr/share/opensearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200/tcp
    restart: always

  graylog:
    image: graylog/graylog:5.1
    container_name: graylog
    environment:
      # CHANGE ME (must be at least 16 characters)!
      GRAYLOG_PASSWORD_SECRET: "somepasswordpepper"
      # Password: admin
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    volumes:
      - "graylog_data:/usr/share/graylog/data"
    restart: always
    depends_on:
      opensearch:
        condition: "service_started"
      mongo:
        condition: "service_started"
    ports:
      - 9000:9000/tcp   # Graylog web interface and REST API
      - 1514:1514/tcp   # Syslog
      - 1514:1514/udp   # Syslog
      - 12201:12201/tcp # GELF
      - 12201:12201/udp # GELF

volumes:
  db-data:
  mongo_data:
  log_data:
  graylog_data: