# Generated by Django 5.0.6 on 2024-05-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=50, null=True)),
                ('merchant', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['data'], name='shipments_s_data_20ab4b_idx'), models.Index(fields=['event'], name='shipments_s_event_e19202_idx')],
            },
        ),
    ]
